apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-deployment
  labels:
    app: queue
    release: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
      release: "1"
  template:
    metadata:
      labels:
        app: queue
        release: "1"
    spec:
      containers:
        - name: fleetman-queue-container
          image: richardchesterwood/k8s-fleetman-queue:release1
          ports:
            - containerPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: queue-service
  labels:
    app: queue
spec:
  type: NodePort
  selector:
    app: queue
    release: "1"
  ports:
    - name: http
      port: 8161   
      targetPort: 8161   
      nodePort: 30010 
    
    - name: endpoint
      port: 61616