apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator-deployment
  labels:
    app: position-simulator
    release: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-simulator
      release: "1"
  template:
    metadata:
      labels:
        app: position-simulator
        release: "1"
    spec:
      containers:
        - name: fleetman-position-simulator-container
          image: richardchesterwood/k8s-fleetman-position-simulator:release1
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "production-microservice"

