apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
    release: "1"
spec:
  containers:
  - name: fleetman-queue-container
    image: richardchesterwood/k8s-fleetman-queue:release1
    ports:
    - containerPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: queue-service
  labels:
    app: queue
spec:
  type: NodePort
  selector:
    app: queue
    release: "1"
  ports:
    - protocol: TCP
      port: 8161        # External service port
      targetPort: 8161   # Port exposed by your container
      nodePort: 30010  # Port exposed on each worker node (must be 30000–32767)