apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
    release: "1"
spec:
  containers:
  - name: fleetman-webapp-container
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-multi
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80         # External service port
      targetPort: 80   # Port exposed by your container
      nodePort: 30080  # Port exposed on each worker node (must be 30000–32767)