apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      release: "1"
  template:
    metadata:
      labels:
        app: webapp
        release: "1"
    spec:
      containers:
      - name: fleetman-webapp-container
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-multi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80         # External service port
      targetPort: 80   # Port exposed by your container
      nodePort: 30080  # Port exposed on each worker node (must be 30000–32767)